name: dev-push-check
run-name: ${{ github.actor }} pushed new code to {{ github.ref }} 💻
on: [push] #, pull_request]
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: install shellcheck
        run: sudo apt-get install -y shellcheck
      - name: checkout repo
        uses: actions/checkout@main
      - name: lint files against shellcheck
        run: make lint_shellcheck
  lint_shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: install shfmt
        run: sudo apt-get install -y shfmt
      - name: checkout repo
        uses: actions/checkout@main
      - name: lint files against shfmt
        run: make lint_shfmt
  test_setup_linux:
    runs-on: ubuntu-latest
    needs:
      - lint_shfmt
      - lint_shellcheck
    steps:
      - name: install soft
        run: sudo apt install -y tmux git
      - name: checkout repo
        uses: actions/checkout@main
      - name: dummy test setup
        run: ./tests/run_all_linux_tests.sh
